- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Key Pair
      amazon.aws.ec2_key:
        name: sample
        region: us-east-1
      register: keyout

        #- name: Display Key
        #debug:
        #var: keyout

    - name: Save Keyout
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
      when: keyout.changed

    - name: start an instance
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "sample"
        #vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
        #network_interfaces:
           #- assign_public_ip: true
        image_id: ami-06b21ccaeff8cd686 		//Amazon AMI ID
        region: us-east-1
        exact_count: 1
        tags:
          Environment: Testing