- name: Provisioning
  hosts: all
  become: yes
  tasks:
    - name: Install ntp on Centos
      yum:
       name: "{{item}}"
       state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - zip
        - unzip
        - git
    - name: Install ntp on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:					//Looping
          - ntp
          - zip
          - unzip
          - git

    - name: Start service on centos
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Banner File
      copy:
        content: "This server is managed by ansible. No manual changes please"
        dest: /etc/motd

    - name: create a folder
      file:
        path: /opt/test123
        state: directory

 - name: Deploy ntp agent config on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
      notify:
        - Restart service on centos

    - name: Deploy ntp agent config on ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/ntpsec/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu" 	//Condition
      notify:				
        - Restart service on Ubuntu			//Handlers name

  handlers:				// execute if any changes
    - name: Restart service on centos
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Restart service on Ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"